-- Rollback initial schema

DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS teams CASCADE;
DROP TABLE IF EXISTS team_members CASCADE;
DROP TABLE IF EXISTS correlations CASCADE;
DROP TABLE IF EXISTS summaries CASCADE;
DROP TABLE IF EXISTS team_summaries CASCADE;
DROP TABLE IF EXISTS fetch_metadata CASCADE;
DROP TABLE IF EXISTS audit_log CASCADE;
DROP TABLE IF EXISTS api_keys CASCADE;

DROP MATERIALIZED VIEW IF EXISTS daily_user_activity;
DROP MATERIALIZED VIEW IF EXISTS weekly_team_activity;
DROP MATERIALIZED VIEW IF EXISTS user_correlation_summary;

DROP TYPE IF EXISTS platform_type;
DROP TYPE IF EXISTS event_type;
DROP TYPE IF EXISTS correlation_type;

DROP EXTENSION IF EXISTS "uuid-ossp";
DROP EXTENSION IF EXISTS "pg_trgm";
DROP EXTENSION IF EXISTS "btree_gin";
DROP EXTENSION IF EXISTS "pg_stat_statements";

