// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Blocked struct {
	Title           string `json:"title"`
	BlockedBy       string `json:"blockedBy"`
	DurationHours   int32  `json:"durationHours"`
	ImpactLevel     string `json:"impactLevel"`
	SuggestedAction string `json:"suggestedAction"`
}

type InProgress struct {
	Title           string  `json:"title"`
	PercentComplete int32   `json:"percentComplete"`
	Blocker         *string `json:"blocker,omitempty"`
	DueDate         *string `json:"dueDate,omitempty"`
}

type Query struct {
}

type UserWeeklyReport struct {
	UserID      string        `json:"userID"`
	Wins        []*Win        `json:"wins,omitempty"`
	InProgress  []*InProgress `json:"inProgress,omitempty"`
	Blocked     []*Blocked    `json:"blocked,omitempty"`
	Notes       *string       `json:"notes,omitempty"`
	GeneratedAt string        `json:"generatedAt"`
}

type Win struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Impact      string `json:"impact"`
}
