// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Blocked struct {
	Title           string `json:"title"`
	BlockedBy       string `json:"blockedBy"`
	DurationHours   int32  `json:"durationHours"`
	ImpactLevel     string `json:"impactLevel"`
	SuggestedAction string `json:"suggestedAction"`
}

type InProgress struct {
	Title           string  `json:"title"`
	PercentComplete int32   `json:"percentComplete"`
	Blocker         *string `json:"blocker,omitempty"`
	DueDate         *string `json:"dueDate,omitempty"`
}

type Query struct {
}

type TeamBlocker struct {
	Title         string   `json:"title"`
	AffectedUsers []string `json:"affectedUsers"`
	Action        string   `json:"action"`
}

type TeamWeeklyReport struct {
	TeamID             string         `json:"teamID"`
	WeekStart          string         `json:"weekStart"`
	WeekEnd            string         `json:"weekEnd"`
	ExecutiveSummary   string         `json:"executiveSummary"`
	VelocityAnalysis   string         `json:"velocityAnalysis"`
	CollaborationNotes string         `json:"collaborationNotes"`
	TeamBlockers       []*TeamBlocker `json:"teamBlockers,omitempty"`
	Recommendations    []string       `json:"recommendations,omitempty"`
	MemberCount        int32          `json:"memberCount"`
	GeneratedAt        string         `json:"generatedAt"`
}

type UserWeeklyReport struct {
	UserID      string        `json:"userID"`
	Wins        []*Win        `json:"wins,omitempty"`
	InProgress  []*InProgress `json:"inProgress,omitempty"`
	Blocked     []*Blocked    `json:"blocked,omitempty"`
	Notes       *string       `json:"notes,omitempty"`
	GeneratedAt string        `json:"generatedAt"`
}

type Win struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Impact      string `json:"impact"`
}
